# Generated by Django 3.2.2 on 2021-05-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_army_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army_name', models.CharField(max_length=150)),
                ('army_rank', models.CharField(max_length=200)),
                ('army_phone', models.CharField(max_length=50)),
                ('army_province', models.CharField(max_length=100)),
                ('army_hint', models.CharField(max_length=800)),
            ],
        ),
    ]
